-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color10 = '#263c2e'
local Color13 = '#746f77'
local Color0 = '#87898f'
local Color6 = '#96E072'
local Color12 = '#3D4352'
local Color3 = '#FFE66D'
local Color4 = '#c74ded'
local Color7 = '#23262E'
local Color8 = '#262A33'
local Color1 = '#00e8c6'
local Color5 = '#ee5d43'
local Color11 = '#3f2834'
local Color9 = '#D5CED9'
local Color2 = '#f39c12'

highlight('Comment', nil, Color0, nil)
highlight('Identifier', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Type', nil, Color3, nil)
highlight('Keyword', nil, Color4, nil)
highlight('Type', nil, Color4, nil)
highlight('Constant', nil, Color5, nil)
highlight('Operator', nil, Color5, nil)
highlight('String', nil, Color6, nil)
highlight('StatusLine', nil, Color7, nil)
highlight('WildMenu', Color8, Color9, nil)
highlight('Pmenu', Color8, Color9, nil)
highlight('PmenuSel', Color9, Color8, nil)
highlight('PmenuThumb', Color8, Color9, nil)
highlight('DiffAdd', Color10, nil, nil)
highlight('DiffDelete', Color11, nil, nil)
highlight('Normal', Color8, Color9, nil)
highlight('Visual', Color12, nil, nil)
highlight('CursorLine', Color12, nil, nil)
highlight('ColorColumn', Color12, nil, nil)
highlight('SignColumn', Color8, nil, nil)
highlight('LineNr', nil, Color13, nil)
highlight('TabLine', Color7, Color13, nil)
highlight('TabLineSel', Color1, Color8, nil)
highlight('TabLineFill', Color7, Color13, nil)
highlight('TSPunctDelimiter', nil, Color9, nil)

link('TSType', 'Type')
link('CursorLineNr', 'Identifier')
link('TSPunctBracket', 'MyTag')
link('TSTagDelimiter', 'Type')
link('TSFuncMacro', 'Macro')
link('Folded', 'Comment')
link('TSFunction', 'Function')
link('TSProperty', 'TSField')
link('TSRepeat', 'Repeat')
link('TelescopeNormal', 'Normal')
link('Conditional', 'Operator')
link('TSKeyword', 'Keyword')
link('TSParameter', 'Constant')
link('TSNamespace', 'TSType')
link('TSConstant', 'Constant')
link('NonText', 'Comment')
link('TSOperator', 'Operator')
link('TSComment', 'Comment')
link('Operator', 'Keyword')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSNumber', 'Number')
link('TSString', 'String')
link('Repeat', 'Conditional')
link('Macro', 'Function')
link('TSLabel', 'Type')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSTag', 'MyTag')
link('TSConditional', 'Conditional')
link('TSField', 'Constant')
link('TSParameterReference', 'TSParameter')
link('Whitespace', 'Comment')
link('TSFloat', 'Number')
link('FoldColumn', 'SignColumn')
